# Generated by Django 6.0.7 on 2026-09-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_social_media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=80),
        ),
    ]
