# Generated by Django 6.0.7 on 2026-09-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_social_media_app', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=2200),
        ),
    ]
